[package]
name = "lets-try-rust"
version = "0.0.0"
authors = ["John Soo <jsoo1@asu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]